#!/bin/bash
#
# Get the HTTP response code for a URL


error(){
    echo "ERROR: $@" >&2
}


if (( $# != 1 )); then
    error "Please supply a valid URL"
    exit 1
fi

url=$1
response=$(curl -Is --connect-timeout 5 --output "/dev/null" --write-out "%{http_code}\n" "$url" 2>/dev/null)

if [[ -z $response ]]; then
    error "No response from '$url'"
    exit 1
elif [[ ! $response =~ ^[1-5][0-9]{2}$ ]]; then
    error "Did not receive a valid response code"
    echo "RESPONSE: $response" >&2
    exit 1
else
    echo "$response"
fi
