#!/bin/bash
#
# Query the hostname of an IP address via dig


error(){
    echo "ERROR: $@" >&2
}

query(){
    if [[ ! $1 =~ ^[1-9][0-9]{,2}(\.[0-9]{1,3}){3}$ ]]; then
        error "'$1' does not appear to be a valid IP address"
        return 1
    elif ! netcheck -i; then
        error "No Internet access"
        return 1
    fi

    local output=$(dig +short -x "$1" 2>/dev/null)
    if [[ -z $output || $output = ';; connection timed out; no servers could be reached' ]]; then
        error "No results"
        return 1
    else
        echo "${output%.}"
    fi
}


if (( $# == 0 )); then
    error "Please indicate a target IP address"
    exit 1
elif [[ $# -eq 1 && $1 =~ ^(-h|--help)$ ]]; then
    echo "Usage: ${0##*/} <IP address>"
    echo "Query the hostname of an IP address via dig."
    exit 0
elif (( $# == 1 )); then
    query "$1"
else
    error "Too many arguments"
    exit 1
fi
