#!/usr/bin/python3
# pylint: disable=no-name-in-module

"""

Prettyprint syntax-highlighted HTML from /dev/stdin

Compatible with Python 2/3

Usage: command | prettyprint

"""


def combo():
    """Return syntax-highlighted prettified HTML."""
    import signal
    import sys

    # ignore broken pipe error
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)

    content = highlight(prettify(sys.stdin.read()))

    # encode to str if necessary (Python 2)
    return content if isinstance(content, str) else content.encode('utf8')


def highlight(html):
    """Return syntax-highlighted HTML."""

    import pygments
    from pygments.lexers import HtmlLexer
    from pygments.formatters import Terminal256Formatter

    args = {'style': 'native'}
    lexer = HtmlLexer(**args)
    formatter = Terminal256Formatter(**args)

    return pygments.highlight(html, lexer, formatter)


def prettify(html):
    """Return prettified HTML."""

    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html)
    return soup.prettify()


print(combo())
